/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import OBJ.NhanVien;
import Utils.ValidateData;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dao Ha
 */
public class frmDangNhap extends javax.swing.JFrame {

    NhanVien nv = new NhanVien();
    ValidateData validate = new ValidateData();
    ArrayList<NhanVien> listNV = new ArrayList<>();

    /**
     * Creates new form Login
     */
    public frmDangNhap() {
        initComponents();
        loadFile();
    }

    static String userName;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    boolean nhoTaiKhoan = false;

    public void loadFile() {
        try {
            BufferedReader br = null;
            FileReader fr = null;
            fr = new FileReader("dangnhap.txt");
            br = new BufferedReader(fr);
            String s = null;

            try {
                while ((s = br.readLine()) != null) {

                    //Cắt chuỗi:
                    String arr[] = s.split("\t");
                    nhoTaiKhoan = Boolean.parseBoolean(arr[2]);
                    //Khởi tạo
                    if (nhoTaiKhoan) {
                        txt_nhoTaiKhoan.setSelected(true);
                        txt_userName.setText(arr[0]);
                        txt_passWord.setText(arr[1]);
                    }

                }
            } catch (IOException ex) {
                Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void saveFile() {

        try {
            BufferedWriter bw = null; //Khởi tạo
            FileWriter fw = null; //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            if (txt_nhoTaiKhoan.isSelected()) {
                data = txt_userName.getText() + "\t" + txt_passWord.getText() + "\t" + txt_nhoTaiKhoan.isSelected();
            }
           
            fw = new FileWriter("dangnhap.txt");
            bw = new BufferedWriter(fw);
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_userName = new javax.swing.JTextField();
        txt_passWord = new javax.swing.JPasswordField();
        txt_nhoTaiKhoan = new javax.swing.JCheckBox();
        btn_dangNhap = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hinh-nen-may-tinh-3.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐĂNG NHẬP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(jLabel1)
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("UserName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 70, -1));

        txt_userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 240, 30));

        txt_passWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passWordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_passWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 240, 30));

        txt_nhoTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nhoTaiKhoan.setText("Nhớ tài khoản");
        getContentPane().add(txt_nhoTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        btn_dangNhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_dangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout-icon.png"))); // NOI18N
        btn_dangNhap.setText("ĐĂNG NHẬP");
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 180, 38));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User-blue-icon (2).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 110, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hinh-nen-may-tinh-3.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 66, 550, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        // TODO add your handling code here:
        saveFile();
        checkUserName_Password();

    }//GEN-LAST:event_btn_dangNhapActionPerformed

    public void checkUserName_Password() {
        frmNhanVien nhanVien = new frmNhanVien();
        userName = txt_userName.getText();
        String passWord = txt_passWord.getText();
        for (int i = 0; i < nhanVien.listNV.size(); i++) {
            if (nhanVien.listNV.get(i).getMaNhanVien().equals(userName) && nhanVien.listNV.get(i).getMatKhau().equals(validate.md5(passWord))) {
                if (nhanVien.listNV.get(i).getTrangThai() == 0) {
                    JOptionPane.showMessageDialog(this, "Nhân viên này đã bị khóa !");
                    return;
                }

                this.dispose();
                frmMain main = new frmMain();
                main.setVisible(true);
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu bị sai ! ");
    }

    private void txt_passWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passWordActionPerformed

    private void txt_userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDangNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox txt_nhoTaiKhoan;
    private javax.swing.JPasswordField txt_passWord;
    private javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables
}
