/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import OBJ.HoaDon;
import OBJ.NhanVien;
import OBJ.SanPham;
import java.awt.Window;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dao Ha
 */
public class ThongKeTheoNgayThang extends javax.swing.JPanel {

    /**
     * Creates new form frmThongKe
     */
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    ArrayList<HoaDon> listHD = new ArrayList<>();
    HoaDon hoaDon = new HoaDon();
    public ThongKeTheoNgayThang() {
        initComponents();
        loadFile();
        getData(listHD);
    }

    public void loadFile() {
        try {
            BufferedReader br = null;
            FileReader fr = null;
            listHD = new ArrayList<>(); //lưu ý
            fr = new FileReader("hoadon.txt");
            br = new BufferedReader(fr);
            String s = null;
            
            try {
                while ((s = br.readLine()) != null) {
                    //Cắt chuỗi:
                    String arr[] = s.split("\t");
                    //Khởi tạo
                    HoaDon hd = new HoaDon();
                    hd.setMaHD(arr[0]);
                    hd.setMaNV(arr[1]);
                    hd.setMaKH(arr[2]);
                    hd.setMaSP(arr[3]);
                    hd.setNgayBan(arr[4]);
                    hd.setDonGia(Double.parseDouble(arr[5]));
                    hd.setSoLuong(Integer.parseInt(arr[6]));
                    hd.setThanhTien(Double.parseDouble(arr[7]));
                    listHD.add(hd);
                }
            } catch (IOException ex) {
                Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }
           

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_TKTNgay = new javax.swing.JButton();
        txt_ngayBan = new com.toedter.calendar.JDateChooser();
        btn_TKTheoThang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongKe = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Zent Coding School");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chart-search-icon.png"))); // NOI18N
        jLabel2.setText("THỐNG KÊ THEO NGÀY THÁNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(180, 180, 180))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ngày tháng năm:");

        btn_TKTNgay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TKTNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Time-And-Date-Plus-1day-icon.png"))); // NOI18N
        btn_TKTNgay.setText("Thống kê theo ngày");
        btn_TKTNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TKTNgayActionPerformed(evt);
            }
        });

        btn_TKTheoThang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_TKTheoThang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar-icon.png"))); // NOI18N
        btn_TKTheoThang.setText("Thống Kê Theo Tháng");
        btn_TKTheoThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TKTheoThangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(txt_ngayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btn_TKTNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TKTheoThang, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ngayBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_TKTNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(btn_TKTheoThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 1060, -1));

        tbl_thongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_thongKe);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 262, 1056, 372));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 97, 191, 24));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Alarm-Error-icon.png"))); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(943, 650, 160, 34));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/111.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void getData(ArrayList<HoaDon> listHD) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã HĐ");
        defaultTableModel.addColumn("Tên sản phẩm");
        defaultTableModel.addColumn("Số lượng");
        defaultTableModel.addColumn("Đơn giá");
        defaultTableModel.addColumn("Thành tiền");

        for (HoaDon hoadon : listHD) {
            Vector vt = new Vector();
            vt.add(hoadon.getMaHD());
            vt.add(new frmBanHang().timKiemTenSPTheoMaSP(hoadon.getMaSP()));
            vt.add(hoadon.getSoLuong());
            vt.add(hoadon.getDonGia());
            vt.add(hoadon.getThanhTien());
            defaultTableModel.addRow(vt);
        }
        tbl_thongKe.setModel(defaultTableModel);
    }
    private void btn_TKTNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TKTNgayActionPerformed
        // TODO add your handling code hereG:
        SimpleDateFormat sdm = new SimpleDateFormat("dd-MM-yyyy");
        String ngayTK = sdm.format(txt_ngayBan.getDate());
        
        ArrayList<HoaDon> listTK = new ArrayList<>();
        for (int i = 0; i < listHD.size(); i++) {
            if(ngayTK.equals(listHD.get(i).getNgayBan())){
                listTK.add(listHD.get(i));  
            }
        }
        getData(listTK);
    }//GEN-LAST:event_btn_TKTNgayActionPerformed

    private void btn_TKTheoThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TKTheoThangActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdm = new SimpleDateFormat("dd-MM-yyyy");
        String ngayTK = sdm.format(txt_ngayBan.getDate());
        String thang = ngayTK.split("-")[1];
        ArrayList<HoaDon> listTK = new ArrayList<>();
        for (int i = 0; i < listHD.size(); i++) {
            if(thang.equals(listHD.get(i).getNgayBan().split("-")[1])){
                listTK.add(listHD.get(i));
            }
        }
        getData(listTK);
    }//GEN-LAST:event_btn_TKTheoThangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JComponent comp = (JComponent) evt.getSource();
        Window win = SwingUtilities.getWindowAncestor(comp);
        win.dispose();
        frmMain main = new frmMain();
        main.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TKTNgay;
    private javax.swing.JButton btn_TKTheoThang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable tbl_thongKe;
    private com.toedter.calendar.JDateChooser txt_ngayBan;
    // End of variables declaration//GEN-END:variables
}
